server:
  port: ${PRODUCT_SERVER_PORT:8050}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: johnny
    password: johnny123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username:johnny}
    password: ${spring.datasource.password:johnny123}
